CREATE TABLE sales(
    id INT UNSIGNED AUTO_INCREMENT,
    client_id INT NOT NULL,
    date TIMESTAMP NOT NULL,
    total DECIMAL(12,2) DEFAULT 0,
    comments TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT FK_sales_client_id FOREIGN KEY (client_id)
      REFERENCES clients(id)
      ON UPDATE CASCADE ON DELETE RESTRICT
);