CREATE TABLE payments_detail(
	id INT NOT NULL AUTO_INCREMENT,
	payments_id INT NOT NULL,
	purchase_id INT UNSIGNED NOT NULL,
	amount DECIMAL(10,2) DEFAULT 0,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);