CREATE TABLE suppliers (
	id INT auto_increment NOT NULL,
	name VARCHAR(250) NULL,
	is_active TINYINT DEFAULT 1 NULL,
	user_id INT UNSIGNED,
	created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP NULL DEFAULT NULL,
	CONSTRAINT suppliers_pk PRIMARY KEY (id),
	CONSTRAINT suppliers_unique UNIQUE KEY (name),
	FOREIGN KEY (user_id)
      REFERENCES users(id)
      ON UPDATE CASCADE ON DELETE RESTRICT
);