CREATE TABLE accounts (
  id INT NOT NULL AUTO_INCREMENT,
  name varchar(250) DEFAULT NULL,
  init_balance DECIMAL(10,2) DEFAULT '0.00',
  is_active TINYINT DEFAULT 1,
  user_id INT UNSIGNED DEFAULT NULL,
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP NULL DEFAULT NULL,
  CONSTRAINT sclients_pk PRIMARY KEY (id),
  FOREIGN KEY (user_id)
      REFERENCES users(id)
      ON UPDATE CASCADE ON DELETE RESTRICT
);